#' This is a function that bined the converted data that generated by the UFT method with the rest of the numerical variables.
#' @param converted_data is the dataframe output of the UFT method.
#' @return return a dataframe with with all the variables are numerical as consequence of using UFT method on the categorical variables
#' @details This is a function that convert the original raw data into binary data set
#' @author Rani Basna
#' @import tidyverse
#' @export
bined_converted_func <-  function(converted_data, original_data){
  scaled_num_data <- original_data %>% select_if(is.double) %>% scale() %>% as.data.frame()
  converted_df <- cbind(converted_data, scaled_num_data)
}
