---
title: "Airway Disease Clustering with decesion tree and unsupervised feature transformation"
output: html_notebook
---

# instaling libraries needed
```{r loadlib, include=FALSE}
mydata <- read.csv('/Users/xbasra/Documents/Data/Airway_Clustering/Original_Data/Airway Disease Phenotyping Data Sets5/WSAS And OLIN Airway Disease Phenotyping.csv')
#library('FactoMineR')
library(tidyverse)
library(treeClust)
library(factoextra)
library(Rtsne)
library(ggplot2)
library(umap)
```

## Preprocessing the dataset for the projection methods as well as scaling the data

```{r}
Airway2 <- Get_Binary_data(mydata)

# scaling with caret average
ordinalCol_Airway <- c('ever_smoker20py', 'dyspneaMRC')
pp <- preProcess(Airway2[Airway_spilts$numeric], method = "range")
pp1 <- preProcess(Airway2[ordinalCol_Airway], method = "range")
scaled_Airway <- Airway2
scaled_Airway[Airway_spilts$numeric]<- predict(pp, Airway2[Airway_spilts$numeric])
scaled_Airway[ordinalCol_Airway] <- predict(pp1, Airway2[ordinalCol_Airway])
# saving the data
write.csv(Airway2, '/Users/xbasra/Documents/Data/Clustering/Results_Data_Reports/CsvData/Airway2.csv')
```


```{r}
# important to set a seed here
set.seed(33)
airway.tc1 <- treeClust(Airway2, d.num = 1, control = treeClust.control(return.trees = TRUE, return.dists = TRUE))
h_tree <- hcut(airway.tc1$dists, 6, isdiss = TRUE, hc_method = 'ward.D2')
table(h_tree$cluster)
```

```{r}
set.seed(10)
# Tsne for tree distacne
tsne_tree_distance <- Rtsne(X = airway.tc1$dists, is_distance = TRUE, check_duplicates = FALSE)

tsne_tree_distance <- tsne_tree_distance$Y %>%
  data.frame() %>%
  setNames(c("X", "Y"))
tsne_tree_distance$cl <- factor(h_tree$cluster)
ggplot(tsne_tree_distance, aes(x=X, y=Y, color=cl)) + geom_point()
```

# UFT

```{r}
set.seed(33)
drops_numerical <-Airway_spilts$numeric
Airway_cate <- Airway2[ , !(names(Airway2) %in% drops_numerical)]

Airway_cate_to_num <- Airway_cate
m <- length(Airway_cate_to_num)
d <- dim(Airway_cate_to_num)[1]
for (j in 1:m) {
  n <- length(unique(Airway_cate[,j])) 
  S <- as.vector(as.matrix(count(Airway_cate, Airway_cate[,j], sort = TRUE)[,1])) # the unique values of variable (we did this some that the order match with count and probabilities)
  C <- as.vector(as.matrix(count(Airway_cate, Airway_cate[,j], sort = TRUE)[,2])) # the count (number of occurance) of the values in the variable
  P <- C/(d*1) # Probabilities
  for (i in 1:n){
    mu <- 0
    L1 <- 0
    L2 <- 1- sum(P^3)
    L3 <- 0
    for (h in 1:n) {
      H <- P[h]*P[i]*(h-i)^2
      L3 <- H + L3
    }
    for (k in 1:i){
      mu1 <- sum((n-k) * P[k])
      L1 <- L1 + mu1
    }
    mu <- ((n -i) - L1) * sqrt(L2/L3)
    for (l in 1:d){
      if (Airway_cate_to_num[l,j] == S[i]){
        Airway_cate_to_num[l,j] <- rnorm(1,mu, P[i])
      }
    }
  }
}
```


```{r}
converted_airway <- bined_converted_func(converted_data = Airway_cate_to_num_only_cate, original_data = Airway2)
#write.csv(Airway_cate_to_num, '/Users/xbasra/Documents/Data/Clustering/Results_Data_Reports/CsvData/converted_UFT.csv')
```

```{r}
set.seed(50)
tsne_converted <- Rtsne(X = converted_airway ,perplexity= 30, is_distance = FALSE, check_duplicates = FALSE)

tsne_converted <- tsne_converted$Y %>%
  data.frame() %>%
  setNames(c("X", "Y"))

ggplot(aes(x = X, y = Y), data = tsne_converted)  + geom_point()
```

- umap
```{r}
set.seed(14)
converted_umap <- umap(converted_airway)

converted_umap <- converted_umap$layout %>%
  data.frame() %>%
  setNames(c("X", "Y"))

ggplot(aes(x = X, y = Y), data = converted_umap)  + geom_point()
```

```{r}
set.seed(111)
k_converted <- kmeans(converted_airway, centers = 6, nstart = 100)
grp_k_converted <- k_converted$cluster
table(grp_k_converted)
```

```{r}
set.seed(222)
converted_umap <- umap(converted_airway)

converted_umap_df <- converted_umap$layout %>%
  data.frame() %>%
  setNames(c("X", "Y"))

converted_umap_df$cluster <- grp_k_converted
ggplot(aes(x = X, y = Y, color = as.factor(cluster)), data = converted_umap_df) +
    geom_point() + scale_color_brewer(palette="Dark2")

```

